notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: bash

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo groupadd mgxserv
  - sudo install -d -m 02755 -g mgxserv /vol/mgx-sw
  - source tools.config

script:
  - set -e ; for fragment in *.build; do bash ${fragment} ; done

