notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: bash

dist: trusty

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo groupadd mgxserv
  - sudo usermod -a -G mgxserv $USER
  - sudo install -d -m 02755 -g mgxserv /vol/mgx-sw
  - source tools.config

script:
  - for fragment in *.build; do 
        bash ${fragment}
        if [ $? != 0 ]; then exit 1 ; fi
    done

