
FROM ubuntu:22.04 AS builder

LABEL version="1.0"
LABEL maintainer="sebastian@jaenicke.org"

# build dependencies
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && apt-get -y install \
    git wget make gcc g++ gfortran libtool zlib1g-dev unzip autoconf file cpio \
    cython3 python3-pip xz-utils libssl-dev pkg-config libffi-dev \
    bzip2 libbz2-dev liblzma5 liblzma-dev libcurl4 libcurl4-openssl-dev cmake \
    libboost-program-options-dev libboost-iostreams-dev \
    libboost-graph-dev libboost-system-dev libboost-filesystem-dev libboost-serialization-dev \
    libgomp1 libxml2 libperl5.34 python-is-python3 python3-minimal python3-numpy

# runtime dependencies
#
# libxml2: magicblast
# libperl5.26: Sys::Hostname for bowtie2
# python: bowtie2
# metabat: boost
# checkm: python-numpy python-pysam python-dendropy python-matplotlib

RUN groupadd mgxserv && useradd -m -g mgxserv mgxserv && chown -R mgxserv /home/mgxserv

COPY . /tmp/tools

ENV PATH="/vol/mgx-sw/bin:${PATH}"

RUN cd /tmp/tools && bash -x base.build && bash -x FRAGMENT.build


FROM ubuntu:22.04 

RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# runtime dependencies
RUN apt-get -y update

RUN groupadd mgxserv && useradd -m -g mgxserv mgxserv && chown -R mgxserv /home/mgxserv

COPY . /tmp/tools
RUN if [ -f /tmp/tools/FRAGMENT.deps ]; then bash -x /tmp/tools/FRAGMENT.deps; fi ; rm -rf /var/lib/apt/lists/* ; rm -rf /tmp/tools

COPY --from=builder /vol/mgx-sw/ /vol/mgx-sw
COPY --from=builder /etc/profile.d/mgx-sw.sh /etc/profile.d/

ENV PATH="/vol/mgx-sw/bin:${PATH}"

USER mgxserv
